name: Hello World CI

on:
  push:
    branches: 
      - main
      - develop
      - 'release/**'
      - "feature/**"
  pull_request:
    branches: 
      - main
      - develop 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: |
          mvn install --file pom.xml
    
    - name: Uploading the image id as artifacts for manaul deployment
    #    if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: my-app-artifact
          path: target/my-app-1.0-SNAPSHOT.jar
          retention-days: 90

    - name: Run a script with secret
      run: echo $MY_SECRET
      env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: Run a script with variable
      run: echo $MY_VARIABLE
      env:
          MY_VARIABLE: ${{ vars.MY_VARIABLE }

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Downloading jar
    - uses: actions/download-artifact@v4
      with:
          name: my-app-artifact

    - name: List the artifacts
      run: | 
         ls -ltr
      
    - name: Deploy to Dev enviormnet
      run: |
         echo "Deployment is done"
      
  deploy_stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
    - name: Deploy to stage enviormnet
      run: |
         echo "Deployment is done"

